DoS Revamp
honeynet/honeyscanner pull request #37
Opened 2024-07-10 04:14 UTC by Swangeon

Go rewrite of the DoS attack in Honeyscanner.

2024-07-11 11:48 UTC, aristofanischionis requested changes
Hi, thanks for the PR, please review my comments and provide the necessary fixes before merging.

2024-07-11 11:48 UTC, aristofanischionis commented on README.md
> +sudo python3 main.py --honeypot cowrie --honeypot_version 2.5.0 --target_ip 127.0.0.1 --port 2222 --username root --password 1234
Let's avoid introducing running honeyscanner with `root` privileges, we are just scanning for open ports, so we can change the nmap flags to only '-p-', this way we can keep running honeyscanner as a normal user.

2024-07-11 11:48 UTC, aristofanischionis commented on .gitignore
> +honeyscanner/active_attacks/attacks/attacks
too many attacks attacks, nested folders, can we improve this?

2024-07-11 11:48 UTC, aristofanischionis commented on README.md
> +sudo python3 main.py --honeypot kippo --honeypot_version 0.9 --target_ip 127.0.0.1 --port 2222
same about sudo

2024-07-11 11:48 UTC, aristofanischionis commented on honeyscanner/active_attacks/attack_orchestrator.py
> +        # For Dionaea and Conpot, we can run the DoS attack only
Is this comment still valid?

2024-07-11 11:48 UTC, aristofanischionis commented on honeyscanner/active_attacks/honeypot_port_scanner/honeypot_port_scanner.py
> +                attack_ports[port] = {
this needs to be adjusted as now we will run a port scan only, not scanning with scripts (-sC) and versions (-sV) which are parts of the (-A) flag. Adjustments need to be made.

2024-07-11 11:48 UTC, aristofanischionis commented on honeyscanner/main.py
> +    if not check_go_exists():
This is not accurate, maybe go is installed in the system but is not in path, it's more accurate to change the error message to something like go is not found in the path. Also we need to consider go compilation on runtime, I am not sure if it's the best idea. Also, providing the compiled binary is also not the best idea, as it won't work in all architectures. Maybe we can provide for amd64 and arm64 and query the system on runtime and determine which one to use.

2024-07-19 10:31 UTC, aristofanischionis commented
@Swangeon Can you please update README with some FAQs to help users. 
In case of troubles, suggest that they install the latest version of anaconda from here
https://www.anaconda.com/download/success
and that they make sure they use python 3.10
and also if they still face problems with pipenv install, they should try emptying their virtualenvs folder and trying again.

Also, don't we need one more line in Pipfile?
`typing = "*"`
to import the typing library?

2024-07-19 10:38 UTC, aristofanischionis commented
DoS attack doesn't seem to be able to take down the honeypot. I am running the Cowrie honeypot in the exact same way I was running it before, with the Python code used before, the honeypot was becoming unavailable, and now with the Go module, not anymore, it is still up.

2024-07-29 11:21 UTC, aristofanischionis commented
I received these 2 warnings when trying to run Honeyscanner, did you also experience them? Let's fix them before merging.

<img width="1429" alt="Screenshot 2024-07-29 at 14 17 59" src="https://github.com/user-attachments/assets/bca1510d-9008-442d-9c44-b63d1adf8509">

2024-07-29 11:29 UTC, aristofanischionis commented
The Honeypot port scanner is not working properly for me. 
We can try integrating this PR (https://github.com/honeynet/honeyscanner/pull/38) and removing nmap altogether as it's slow, noisy, and too big for what we need.

<img width="590" alt="Screenshot 2024-07-29 at 14 26 38" src="https://github.com/user-attachments/assets/f15b0340-b7ec-4cea-a56d-478215d231a4">

2024-07-29 17:20 UTC, Swangeon commented
> I received these 2 warnings when trying to run Honeyscanner, did you also experience them? Let's fix them before merging.
> <img alt="Screenshot 2024-07-29 at 14 17 59" width="1429" src="https://private-user-images.githubusercontent.com/15021868/353025332-bca1510d-9008-442d-9c44-b63d1adf8509.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNzA4ODQsIm5iZiI6MTcyMjI3MDU4NCwicGF0aCI6Ii8xNTAyMTg2OC8zNTMwMjUzMzItYmNhMTUxMGQtOTAwOC00NDJkLTljNDQtYjYzZDFhZGY4NTA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDE2Mjk0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyNWUyYmM1MzczY2ViMWFkN2JjNmVkYmNmNTYxOGE5MTAyMTAyNTM1MjI1ZDg2ZTc5NGYxNmZiNmI0MTQzNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CiKzlX9CGFp3kMCSOd9zBlkLu8NCiKDMSFFSRCHHWlo">

This is going to be an annoying error for now that doesn't effect the project that you can look at more [here](https://github.com/paramiko/paramiko/issues/2419). There are ways to repress the warning, but I don't know if we would want to implement a temporary solution for a temporary problem.

> The Honeypot port scanner is not working properly for me. We can try integrating this PR (#38) and removing nmap altogether as it's slow, noisy, and too big for what we need.
> <img alt="Screenshot 2024-07-29 at 14 26 38" width="590" src="https://private-user-images.githubusercontent.com/15021868/353027385-f15b0340-b7ec-4cea-a56d-478215d231a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNzA4ODQsIm5iZiI6MTcyMjI3MDU4NCwicGF0aCI6Ii8xNTAyMTg2OC8zNTMwMjczODUtZjE1YjAzNDAtYjdlYy00Y2VhLWE1NmQtNDc4MjE1ZDIzMWE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDE2Mjk0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3YjljNjhhMzg1YzY4N2JiODZhZGM5NGNjZDE1MWVkYzgzYTllOWYwOTg2YjEzNmE5ODhlNDg3MTQ3ZTk5YTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d9zqpPNISTduhnmvMQ-0-RCZdRtBQ9nM6yr7nyQbohE">

I haven't gotten this error before so I am not quite sure whats causing it but I will look into it. I'm not quite certain merging this PR with @ZupaPomidorowa's PR would be best for now because this PR would now have to wait for their PR to be merged and functional to work more on this. If you want, I can just move on to the fuzzing upgrades we talked about and come back to this at a later date.

2024-08-22 13:00 UTC, aristofanischionis requested changes
I am facing some issues while running this version of Honeyscanner
<img width="486" alt="Screenshot 2024-08-22 at 14 53 35" src="https://github.com/user-attachments/assets/3e6e5fed-2a73-4b17-81fd-39ab36bfe4f8">
<img width="1174" alt="Screenshot 2024-08-22 at 14 53 46" src="https://github.com/user-attachments/assets/fba01357-840f-40dc-b4c2-6e3dbb7ffa8e">
<img width="1163" alt="Screenshot 2024-08-22 at 14 53 59" src="https://github.com/user-attachments/assets/d42533ba-cb6e-423e-aaec-e754474696e8">

and dos attack seems to not be working anymore

2024-08-22 13:00 UTC, aristofanischionis commented on README.md
> +- After running a Honeypot using Docker containers locally, you will be able to specify the target ip parameter with `--target_ip 127.0.0.1` when running the Honeyscanner.
there is a typo here, correct is to have target-ip not target_ip

2024-08-22 13:00 UTC, aristofanischionis commented on README.md
> +python3 main.py --target_ip 127.0.0.1
same here

2024-08-22 13:00 UTC, aristofanischionis commented on README.md
> +python3 main.py --target_ip 127.0.0.1 --username root --password 1234
same here

2024-08-22 13:00 UTC, aristofanischionis commented on README.md
> +## FAQ
i like that!

2024-08-22 13:00 UTC, aristofanischionis commented on .gitignore
> +.zed/
what is this for?

2024-08-22 13:00 UTC, aristofanischionis commented on .gitignore
> +*.db-journal
what is this for?

2024-08-25 08:19 UTC, aristofanischionis approved these changes
Thank you for the great work and completing successfully Google Summer of Code 2024. We are glad we had you as part of our team!
Good luck in your future endeavours.

2024-08-25 08:19 UTC, merged